### ISSUE TITLE
Boot loop (solved).

### ISSUE THREAD

**Issue by mkrawcz1** [ihormelnyk/opentherm_library#24]
Hi :-)
My ESP8266s keep rebooting after "OpenThermMaster_Demo.ino" upload with message:
"
ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
"
My environment:
- ESP-12E (different modules),
- Arduino v. 1.8.12, ESP8266 v. 2.6.3, 
- OpenTherm v. 1.1.0,
- inPin = 4,
- outPin = 5.

Please help :-)
Regards
MK

**Comment by ihormelnyk** [comment]
Hi @mkrawcz1,
Try to use ICACHE_RAM_ATTR attribute:
void ICACHE_RAM_ATTR handleInterrupt(

**Comment by mkrawcz1** [comment]
It seems that it solved the problem :-)

**Comment by mkrawcz1** [comment]
Hi
Another issue... I'm trying to interface with De Dietrich MCA 35 Innovens, which claims it's compatible with OpenTherm. The issue is that after a few successfull answers from boiler I'm experiencing no answers for following messages. I'm using template sketch "OpenThermMaster_Demo.ino". Anyone had success witch interfacing this boiler?
