### ISSUE TITLE
SetActiveState and SetIdleState are inverted

### ISSUE THREAD

**Issue by vsezima** [ihormelnyk/opentherm_library#28]
Hello, I noticed that these two functions should be inverted, since in OpenTherm documentation, idle state is defined as LOW level and active state as HIGH level. 

I'm not sure how this works with real boilers and thermostats, because I only tried this library between two ESP8266 (one as boiler/slave, one as thermostat/master, tested also with ESP32) and with original code, messages received on slave were vastly different than those sent from master. And after I inverted these two functions, it worked perfectly and messages were correct.

**Comment by ihormelnyk** [comment]
Hi @vsezima ,
OpenTherm Library is made to work with OpenTherm Adapter http://ihormelnyk.com/opentherm_adapter hardware. So, you should set High level to activate Low level on the hardware level according to the OpenTherm documentation.
