### ISSUE TITLE
OpenThermMessageID 50 missing 

### ISSUE THREAD

**Issue by EmileSpecialProducts** [ihormelnyk/opentherm_library#62]
You are missing the id 50 in the OpenThermMessageID
HcratioUBHcratioLB = 50,                          // s8/s8   OTC heat curve ratio upper & lower bounds for adjustment

**Comment by ihormelnyk** [comment]
Hi @EmileSpecialProducts ,
ID 50 and 58 removed (OTC heat curve items) in OT version 2.3 from August 2005

**Comment by EmileSpecialProducts** [comment]
Thanks for the feedback, i only have the 2.2 Version of the OpenTherm Specs.
