### ISSUE TITLE
Setting the correct temperature and controlling central heating

### ISSUE THREAD

**Issue by Tommrodrigues** [ihormelnyk/opentherm_library#8]
Hi there,

I love this project and have really enjoyed playing around with it. I've successfully been able to interface with my boiler and have been able to do a few things like getting and setting the temperature. My aim with the project is to integrate it with [homebridge-thermostat](https://github.com/PJCzx/homebridge-thermostat) using a NodeMCU in order to expose it to my iPhone. 

Like I mentioned, I have been successfully able to use some of the functionality of your library but still have 4 questions remaining:

1.  When returning the statuses of things like the flame and the central heating, everything seems normal (`on`). However, `Hot Water` get reported as off, which it is not. This is not too much of an issue because the hot water still seems to work fine from taps but I thought it was curious. Is is that my boiler does have the ability to manage the `Hot Water` and this is why it appears as off?

2. During the summer, how do I turn off the central heating whilst retaining hot water? I have tried setting `bool enableCentralHeating = false;` then calling `ot.setBoilerStatus(enableCentralHeating, enableHotWater, enableCooling);` again yet the `Central Heating` stays on. Is it possible to turn off the central heating or is it the case that I need to set the temperature to a really low value or something of that nature?

3. What exactly is boiler `cooling`? I see that it is a status you can check (mine shows as off no matter what temperature is set), yet once again, as with `enableCentralHeating`, `enableCooling` seems to be another thing I can't control with the steps mentioned above. Is this once again functionality that my boiler doesn't have?

4. Finally, and most difficulty I suppose; if I would like to set the house temperature to 23 C for example, how do I control the boiler in such a way to achieve this? As in, I would assume that I need a thermometer as mentioned in your [guide](http://ihormelnyk.com/opentherm_thermostat), yet it is not clear how I would go from the raw current temperature of the room to the temperature I would need to set the boiler. Surely it is not the case that you just turn on the boiler to full until you reach the desired temperature then repeat this if the temperature drops below that temperature? I have tried reading through your Arduino code on the [guide](http://ihormelnyk.com/opentherm_thermostat) and have seen that you set the temperature to `op`, yet it is not clear exactly how you derive this number.

I feel that much of my confusion comes from a lack of understanding of how exactly to use your library which is why I was hoping that you could help.

Thank you in advance for your help,

Kind regards, Tom

**Comment by shimopus** [comment]
Hi @Tommrodrigues 

Let me answer some questions as I was spent some time to investigate.

> During the summer, how do I turn off the central heating whilst retaining hot water?

The only way which is working for me is set the Temperature to less then 40 degrees by Celcium - as it is lowest threshold for my boiler.

> What exactly is boiler cooling?

As this protocol is a general one for a huge amount of different type of "boilers" this thing will work only for that ones which is supporting heating and cooling. So the answer - yes, your boiler doesn't support cooling.

> if I would like to set the house temperature to 23 C for example, how do I control the boiler in such a way

This is a simple PID-controller implementation with predefined coefficients. For more information please read https://en.wikipedia.org/wiki/PID_controller

**Comment by Tommrodrigues** [comment]
@shimopus Thank you so much for your reply,

That's clarified a lot for me. Makes sense that setting the temperature below a threshhold will 'turn off' the central heating. This shouldn't affect tap water temperature should it? 

The PID controller makes sense, I'll look at his code again and see how I can adapt it for my case.

I suppose the only question I have remaining is what exactly are the `enableCentralHeating, enableHotWater, enableCooling` functions for? Are they just to retain connection with the boiler and don't play any real role?

As for which firmware I used, I'm unsure exactly what you mean. I flashed the NodeMCU with the Arduino IDE at the newest board version etc.

Thank you once again for your help,

Kind regards, Tom

**Comment by shimopus** [comment]
@Tommrodrigues you've said

> This shouldn't affect tap water temperature should it?

If you'll change only the heating temperature that the answer is not it will not change the hot water temperature settings.

**Comment by ihormelnyk** [comment]
Hi @Tommrodrigues ,
My boiler Buderus Logamax u072-24k supports only central heating control.
And setBoilerStatus with enableCentralHeating = false turns off central heating.

**Comment by Tommrodrigues** [comment]
@ihormelnyk @shimopus  Strangely, it seems that `setBoilerStatus` with `enableCentralHeating = false` doesn't turn off my central heating; however, as suggested, setting the temperature to `0` does this. Furthermore, even with the temperature set to `0`, the hot water (taps) seem to work as expected thankfully. Thank you once again for your help, I'll be sure to carry on fiddling with the library!

Kind regards, Tom
